providers = ["node"]

[vars]
NODE_VERSION = "20"

[ phases.install ]
cmds = [
  "cd server",
  "npm install --ignore-scripts --legacy-peer-deps"
]

[ phases.build ]
cmds = ["cd server && npm run build"]

[start]
cmd = "cd server && npm start"
