providers = ["node"]

[vars]
NODE_VERSION = "20"
HUSKY = "0"

[ phases.install ]
cmds = [
  "cd server",
  "npm install --legacy-peer-deps"
]

[ phases.build ]
cmds = ["npm run build"]

[start]
cmd = "npm start"
