providers = ["node"]

[ phases.setup ]
env = {
  NODE_VERSION = "20"
}

[ phases.install ]
cmds = [
  "cd server",
  "npm config set ignore-scripts true",
  "npm install --legacy-peer-deps"
]

[ phases.build ]
cmds = ["cd server && npm run build"]

[start]
cmd = "cd server && npm start"
