[build]
  builder = "NIXPACKS"
  buildCommand = "cd server && npm install && npm run build"
  buildCache = false

[deploy]
  numReplicas = 1
  restartPolicyType = "ON_FAILURE"
  restartPolicyMaxRetries = 10
